# Generated by Django 2.0.13 on 2021-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetails',
            name='mobile_no',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
