# Generated by Django 2.0.13 on 2021-01-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0002_auto_20210127_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='farmerDetails',
            new_name='farmerDetail',
        ),
    ]
