# Generated by Django 3.1.5 on 2021-01-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0003_auto_20210127_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetail',
            name='pincode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
