# Generated by Django 3.1.5 on 2021-01-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0004_farmerdetail_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetail',
            name='crop_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmerdetail',
            name='farm_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='farmerdetail',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
