# Generated by Django 3.1.5 on 2021-01-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0005_auto_20210128_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdetail',
            name='pincode',
        ),
    ]
