# Generated by Django 3.1.5 on 2021-01-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0006_remove_farmerdetail_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetail',
            name='farmerName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
