# Generated by Django 3.1.5 on 2021-01-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0007_farmerdetail_farmername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdetail',
            name='farmerName',
        ),
    ]
