# Generated by Django 3.1.5 on 2021-01-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0009_auto_20210128_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetail',
            name='current_time',
            field=models.TimeField(null=True),
        ),
    ]
