# Generated by Django 2.1.15 on 2021-03-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0012_auto_20210301_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetail',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetail',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
