# Generated by Django 2.1.15 on 2021-03-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0013_auto_20210301_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetail',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetail',
            name='current_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
