# Generated by Django 2.0.12 on 2021-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0014_auto_20210302_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50)),
                ('total_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.CharField(blank=True, max_length=50, null=True)),
                ('total_price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
