# Generated by Django 2.0.12 on 2021-03-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_storage', '0016_invoice_month_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
